[package]
name = "mean-median-mode"
version = "0.1.0"
authors = ["Vladimir Smyshliaev <vladimirs@unity3d.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
